POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5paWxvMjIiLCJpZCI6IjVmODA2Yjk2MmRiYjE5MzRjNTY1MDU3MSIsImlhdCI6MTYwMjQwODI5MH0.zLj8jYoRe3bzLqFnWZka-llZAhbp0GxcbVI-qPt2P3E

{
  "author":"213"
}